name: api-client-php CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CLOUDFOREST_HOST: https://cfdev.cloudforest.market
  CLOUDFOREST_API: https://cfdev.cloudforest.market

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout ${{ github.ref }}
      uses: actions/checkout@v3

    - name: Install dependencies
      uses: php-actions/composer@v6

    - name: PHP CS Fixer Check
      run: composer run phpcs:check

    - name: PHPStan
      run: composer run phpstan

    - name: PHPUnit
      run: composer run phpunit
