name: api-client-php CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CLOUDFOREST_HOST: https://cfdev.cloudforest.market
  CLOUDFOREST_API: https://cfdev.cloudforest.market
  CLOUDFOREST_CLIENT_ID: ${{ secrets.CLOUDFOREST_CLIENT_ID }}
  CLOUDFOREST_CLIENT_SECRET: ${{ secrets.CLOUDFOREST_CLIENT_SECRET }}
  CLOUDFOREST_EMAIL: ${{ secrets.CLOUDFOREST_EMAIL }}
  CLOUDFOREST_PASS: ${{ secrets.CLOUDFOREST_PASS }}

jobs:
  ci:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout ${{ github.ref }}
      uses: actions/checkout@v3

    - name: Install dependencies
      uses: php-actions/composer@v6

    - name: Dump autoload
      uses: php-actions/composer@v6
      with:
        command: dump-autoload
        only_args: --no-interaction --classmap-authoritative

    - name: PHP CS Fixer Check
      run: composer run phpcs:check

    - name: PHPStan
      run: composer run phpstan

    - name: PHPUnit
      run: composer run phpunit
